Traceback (most recent call last):
  File "rpc_server.py", line 52, in <module>
    server.serve()
  File "/home/lixiaojun/workspace/python/cyepusher/libs/jsonrpc.py", line 1071, in serve
    self.__transport.serve( self.handle, n )
  File "/home/lixiaojun/workspace/python/cyepusher/libs/jsonrpc.py", line 809, in serve
    self.s.bind( self.addr )
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
